### ISSUE TITLE
TypeError: Cannot set property 'openid-connect' of undefined

### ISSUE THREAD

**Issue by Roboroads** [deeplay-io/verdaccio-openid-connect#1]
I have an error using this plugin -

verdaccio_1  |  error--- error loading a plugin openid-connect: TypeError: Cannot set property 'openid-connect' of undefined
verdaccio_1  |     at new OidcPlugin (/opt/verdaccio/node_modules/verdaccio-openid-connect/lib/index.js:18:54)
verdaccio_1  |     at /opt/verdaccio/build/lib/plugin-loader.js:125:32
verdaccio_1  |     at Array.map (<anonymous>)
verdaccio_1  |     at loadPlugin (/opt/verdaccio/build/lib/plugin-loader.js:62:37)
verdaccio_1  |     at Auth._loadPlugin (/opt/verdaccio/build/lib/auth.js:54:38)
verdaccio_1  |     at new Auth (/opt/verdaccio/build/lib/auth.js:44:25)
verdaccio_1  |     at defineAPI (/opt/verdaccio/build/api/index.js:43:16)
verdaccio_1  |     at _default (/opt/verdaccio/build/api/index.js:127:10)
verdaccio_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by aikoven** [comment]
Which version of Verdaccio are you using?

**Comment by Roboroads** [comment]
Latest - 4.11.0

**Comment by aikoven** [comment]
Just published a fix, please try `verdaccio-openid-connect@1.0.1`

**Comment by Roboroads** [comment]
Fixes this problem, but others have come up - I'll create some tickets :)
