### ISSUE TITLE
Compatibility with latest verdaccio?

### ISSUE THREAD

**Issue by LoicGombeaud** [deeplay-io/verdaccio-openid-connect#12]
Hi! Thanks for this plugin :)

I've noticed that in the Dockerfile you provide, you're using as base image verdaccio 4.10.0; is the plugin also compatible with the latest versions of verdaccio, namely 5.x.x?

Cheers,
Loïc

**Comment by aikoven** [comment]
Hey, yes, it should be compatible. Try it out, and if you encounter any issues — feel free to report them here.

**Comment by LoicGombeaud** [comment]
Thanks for your response, I confirm that it worked with 5.5.0 :tada:

**Comment by aikoven** [comment]
Thanks for your research! I will add this info to the readme.
