### ISSUE TITLE
Server does not support PKCE

### ISSUE THREAD

**Issue by Roboroads** [deeplay-io/verdaccio-openid-connect#2]
I'm using a gitlab instance as openid provider, i'm getting the following error when trying to log in

verdaccio_1  | OPError: invalid_request (Invalid code_verifier parameter. Server does not support pkce.)
verdaccio_1  |     at processResponse (/opt/verdaccio/node_modules/openid-client/lib/helpers/process_response.js:45:13)
verdaccio_1  |     at Client.grant (/opt/verdaccio/node_modules/openid-client/lib/client.js:1237:26)
verdaccio_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
verdaccio_1  |     at async Client.callback (/opt/verdaccio/node_modules/openid-client/lib/client.js:460:24)
verdaccio_1  |     at async /opt/verdaccio/node_modules/verdaccio-openid-connect/lib/index.js:140:34

Or am I dumb and do i need to install something?

**Comment by aikoven** [comment]
It seems that PKCE is not needed for this case, I'll try to disable it, or even use Implicit Grant instead of Authorization Code Grant.

**Comment by Roboroads** [comment]
Or make it an option - fitting more use cases :)

**Comment by aikoven** [comment]
Please try the new version — `verdaccio-openid-connect@1.0.2`.
