### ISSUE TITLE
internal server error on oidc/callback

### ISSUE THREAD

**Issue by ganeshsacharya** [deeplay-io/verdaccio-openid-connect#20]
I am trying to use this plugin with Azure AD and when try logging in it launches the browser and post entering the right credentials, it tries to call the oidc callback url which gives "Internal server error" saying "OPError: invalid_client (AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.

Any hints on what i could be missing?

**Comment by aikoven** [comment]
You should be able to switch the client type from `public` to `confidential` somewhere in the Azure admin console.

**Comment by ganeshsacharya** [comment]
> You should be able to switch the client type from `public` to `confidential` somewhere in the Azure admin console.

Got it :) and it did work. The Azure help texts are little misleading though which put me on a wrong path.

I have 1 more question: now that my oidc login works i no longer can login to the web client of the registry.

Any idea how to resolve that?

**Comment by aikoven** [comment]
I'm not sure, because we don't use the web UI in my company. A possible way is to have two separate clients.

**Comment by ganeshsacharya** [comment]
> I'm not sure, because we don't use the web UI in my company. A possible way is to have two separate clients.

Got you. Thanks a lot. I think i have enough to continue :)
