### ISSUE TITLE
Authentication with keycloak

### ISSUE THREAD

**Issue by melkosoft** [deeplay-io/verdaccio-openid-connect#3]
Trying to configure Verdaccio to use keycloak (docker-compose).
  auth: {
    'openid-connect': {
      publicUrl: 'http://verdaccio:4873',
      redisUri: 'redis',
      issuer: 'http://keycloak:8080/auth/realms/verdaccia/',
      clientId: 'verdaccio',
      clientSecret: 'dfbe390e-ea07-4c6d-b287-c0fd6007cddd',
      usernameClaim: 'preferred_username'
    }
  }
Configured keycloak:
      "id": "4a26062f-55d0-4ac3-a7b7-749ffce4cf6a",
      "clientId": "verdaccio",
      "surrogateAuthRequired": false,
      "enabled": true,
      "alwaysDisplayInConsole": false,
      "clientAuthenticatorType": "client-secret",
      "secret": "dfbe390e-ea07-4c6d-b287-c0fd6007cddd",
      "redirectUris": [
        "http://verdaccio:4873/oidc/callback"
      ]
Started keycloak first, wait to container to be ready (login and check config)
Started verdaccio with redis. Log from verdaccio:
 debug--- [local-storage/_sync]: init sync database
 debug--- [local-storage/_sync]: folder /verdaccio/storage created succeed
 debug--- [local-storage/_sync/writeFileSync]: sync write succeed
 debug--- [local-storage/_sync]: init sync database
 debug--- [local-storage/_sync]: folder /verdaccio/storage created succeed
 debug--- [local-storage/_sync/writeFileSync]: sync write succeed
 warn --- Plugin successfully loaded: verdaccio-openid-connect
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- Plugin successfully loaded: verdaccio-openid-connect
 trace--- local-storage: [get] full list of packages (0) has been fetched
 trace--- local-storage: [get] full list of packages (0) has been fetched
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/4.11.3
 info <-- 172.31.0.1 requested 'GET /'
 http <-- 200, user: null(172.31.0.1), req: 'GET /', bytes: 0/562
 info <-- 172.31.0.1 requested 'GET /-/verdaccio/packages'
 trace--- local-storage: [get] full list of packages (0) has been fetched
 http <-- 304, user: null(172.31.0.1), req: 'GET /-/verdaccio/packages', bytes: 0/0
 info <-- 172.31.0.1 requested 'POST /-/verdaccio/login'

Pressed <Login> button - did not get redirected to keycloak, input user/pwd - failed. Log from verdaccio:

 trace--- authenticating mmamaenko
 trace--- authenticating mmamaenko
 trace--- authenticating for user mmamaenko failed. Error: bad username/password, access denied
 http <-- 401, user: null(172.31.0.1), req: 'POST /-/verdaccio/login', error: bad username/password, access denied
 info <-- 172.31.0.1 requested 'POST /-/verdaccio/login'
 trace--- authenticating mmamaenko
 trace--- authenticating mmamaenko
 trace--- authenticating for user mmamaenko failed. Error: bad username/password, access denied
 http <-- 401, user: null(172.31.0.1), req: 'POST /-/verdaccio/login', error: bad username/password, access denied

When using keycloak with other openid clients I got redirected to keycloak login page but not this time. What is wrong with my config? I can ping all containers by name and I got response from http://keycloak:8080/auth/realms/verdaccia/.well-known/openid-configuration.

**Comment by aikoven** [comment]
> input user/pwd - failed

Do I understand correctly that you input username and password in console? What command do you run?

This plugin only affects `npm login` command from the console. It doesn't currently work with Verdaccio web application login.

**Comment by melkosoft** [comment]
I see, sorry I was using web login, didn't know that it is not working with http. Will test npm login later. Will try to use some openid connectors in front of verdaccio for web login
One question: is your auth plugin compatible with groupnames plugin ( deinstapel /verdaccio-groupnames )?

**Comment by aikoven** [comment]
> One question: is your auth plugin compatible with groupnames plugin ( deinstapel /verdaccio-groupnames )?

Right now, I don't think so. Currently we only add username to the list of groups, see https://github.com/deeplay-io/verdaccio-openid-connect/blob/v1.0.2/src/index.ts#L182
But if we figure out how to get the actual list of groups from OIDC provider, it should be an easy fix.

**Comment by dafanasiev** [comment]
Its really easy to add this feature (see #5).

You also need to configure keycloak roles mapper: add buildin `User Client Role` mapper in client `Mappers` tab with this props:
1. Client Id - you client
2. Client Role prefix  - empty string
3. Multivalued - checked
4. Token Claim Name - roles
5. Claim JSON Type - string
6. Add to ID toke - checked
7. Add to access token - checked
8. Add to userinfo  - you choice
