### ISSUE TITLE
Authentication don't work when verdaccio is hosted on a sub-directory

### ISSUE THREAD

**Issue by KAW0** [deeplay-io/verdaccio-openid-connect#4]
It's works perfect when verdaccio is served on hostname but when I use subdirectory it is ignored.

https://host.name/oidc/login/code

Should be:

https://host.name/packages/oidc/login/code

And yes I changed Gitlab config before testing subdirectory.
[config.yaml.txt](https://github.com/deeplay-io/verdaccio-openid-connect/files/7928337/config.yaml.txt)
[nginx_verdaccio.conf.txt](https://github.com/deeplay-io/verdaccio-openid-connect/files/7928339/nginx_verdaccio.conf.txt)

**Comment by aikoven** [comment]
Please try the new version — `verdaccio-openid-connect@1.0.3`.

Make sure to include a trailing slash after subpath in `publicUrl`:

```yaml
auth:
  openid-connect:
    publicUrl: https://host.name/packages/
```

**Comment by KAW0** [comment]
Address is ok now but server return "internal server error"
>{"level":50,"time":1643137246541,"pid":7,"hostname":"dc63742b3240","err":{"type":"TypeError","message":"id_token not present in TokenSet","stack":"TypeError: id_token not present in TokenSet\n    at TokenSet.claims (/opt/verdaccio/.yarn/cache/openid-client-npm-4.9.1-ead5a0b4ca-0801f82b91.zip/node_modules/openid-client/lib/token_set.js:43:13)\n    at OidcPlugin.getUsername (/opt/verdaccio/.yarn/cache/verdaccio-openid-connect-npm-1.0.3-cf0593ddf2-72402dbf16.zip/node_modules/verdaccio-openid-connect/lib/index.js:63:35)\n    at /opt/verdaccio/.yarn/cache/verdaccio-openid-connect-npm-1.0.3-cf0593ddf2-72402dbf16.zip/node_modules/verdaccio-openid-connect/lib/index.js:136:39\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"},"msg":"unexpected error: @{!err.message}\n@{err.stack}"}

It still works without a subdirectory.

**Comment by aikoven** [comment]
This happens because Nginx regex location does not capture query parameters, so they are not passed to Verdaccio.

Change it to:

```
location ~ ^/packages/(.*)$ {
  proxy_pass http://172.26.0.5:4873/$1?$args;
```

or configure it without regex:

```
location /packages/ {
  proxy_pass http://172.26.0.5:4873/;
```

**Comment by KAW0** [comment]
Works like a charm. Thank you very much.

**Comment by aikoven** [comment]
Glad it helped!
